package com.f5.model.base;

import java.util.Date;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.real_name
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.employee_no
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String employeeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.dept
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.email
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id_card_no
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.mobile
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.city
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private Integer city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.post
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_time
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.creator
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.auditor
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.audit_time
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.audit_status
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private String auditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.account_status
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private Integer accountStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.member_id
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    private Long memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.real_name
     *
     * @return the value of admin.real_name
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.real_name
     *
     * @param realName the value for admin.real_name
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.employee_no
     *
     * @return the value of admin.employee_no
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getEmployeeNo() {
        return employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.employee_no
     *
     * @param employeeNo the value for admin.employee_no
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo == null ? null : employeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.dept
     *
     * @return the value of admin.dept
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.dept
     *
     * @param dept the value for admin.dept
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.email
     *
     * @return the value of admin.email
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.email
     *
     * @param email the value for admin.email
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id_card_no
     *
     * @return the value of admin.id_card_no
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id_card_no
     *
     * @param idCardNo the value for admin.id_card_no
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.mobile
     *
     * @return the value of admin.mobile
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.mobile
     *
     * @param mobile the value for admin.mobile
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.city
     *
     * @return the value of admin.city
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.city
     *
     * @param city the value for admin.city
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.post
     *
     * @return the value of admin.post
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.post
     *
     * @param post the value for admin.post
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_time
     *
     * @return the value of admin.create_time
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_time
     *
     * @param createTime the value for admin.create_time
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.creator
     *
     * @return the value of admin.creator
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.creator
     *
     * @param creator the value for admin.creator
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.auditor
     *
     * @return the value of admin.auditor
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.auditor
     *
     * @param auditor the value for admin.auditor
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.audit_time
     *
     * @return the value of admin.audit_time
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.audit_time
     *
     * @param auditTime the value for admin.audit_time
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.audit_status
     *
     * @return the value of admin.audit_status
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.audit_status
     *
     * @param auditStatus the value for admin.audit_status
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.account_status
     *
     * @return the value of admin.account_status
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public Integer getAccountStatus() {
        return accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.account_status
     *
     * @param accountStatus the value for admin.account_status
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setAccountStatus(Integer accountStatus) {
        this.accountStatus = accountStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.member_id
     *
     * @return the value of admin.member_id
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.member_id
     *
     * @param memberId the value for admin.member_id
     *
     * @mbggenerated Fri Sep 07 16:15:54 CST 2018
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }
}