package com.f5.model.base;

public class Roles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.id
     *
     * @mbggenerated Fri Sep 07 16:51:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.rolename
     *
     * @mbggenerated Fri Sep 07 16:51:36 CST 2018
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.id
     *
     * @return the value of roles.id
     *
     * @mbggenerated Fri Sep 07 16:51:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.id
     *
     * @param id the value for roles.id
     *
     * @mbggenerated Fri Sep 07 16:51:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.rolename
     *
     * @return the value of roles.rolename
     *
     * @mbggenerated Fri Sep 07 16:51:36 CST 2018
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.rolename
     *
     * @param rolename the value for roles.rolename
     *
     * @mbggenerated Fri Sep 07 16:51:36 CST 2018
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }
}